server:  
  port: ${PORT:2222}

spring:  
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost:33306/datagrid?useSSL=false
    username: datagrid
    password: datagrid
  jpa:
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        cache:
#          use_query_cache: true
#          use_second_level_cache: true
#          hazelcast:
#            use_native_client: true
#            native_client_address: 192.168.99.100:5701
#            native_client_group: dev
#            native_client_password: dev-pass
#          region:
#            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            
#logging:
#  level:
#    com.hazelcast: DEBUG
#    org.hibernate: DEBUG